# This is a basic workflow to help you get started with Actions

name: Actualiza Balance Vacunacion

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
    workflow_dispatch:
    schedule:
      - cron:  '15 13 * * *'
      # Allows you to run this workflow manually from the Actions 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Actualiza_productos_vacunacion:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: 'Check out our repo'
      uses: actions/checkout@v2
      with:
          path: Datos-COVID19

    - name: 'Check out vacunas'
      uses: actions/checkout@v2
      with:
          repository: MinCiencia/Vacunacion
          token: ${{ secrets.PRIVATE_PAT }}
          path: Vacunacion

      # Sets up python
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
          python-version: 3.8

    # Runs a set of commands using the runners shell

    - name: transfer files
      run: |
          pwd
          ls
          ls -la Datos-COVID19/input/Vacunacion
          rsync -auH Vacunacion/output/Vacunacion/. Datos-COVID19/input/Vacunacion
          ls -la Datos-COVID19/input/Vacunacion

    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip install -r Datos-COVID19/requirements.txt

    - name: generate products from Informe Epidemiologico
      run: |
        cd Datos-COVID19/src
        python vacunacion.py &&\
        python tweet.py ${{ secrets.TWITTER_API_KEY }} ${{ secrets.TWITTER_API_SECRET }}  \
                              ${{ secrets.TWITTER_ACCESS_TOKEN }}  ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }} \
                              vacunacion

    - uses: stefanzweifel/git-auto-commit-action@v4.1.1
      with:
        commit_message: "Added data from FTP to repo, updated campana #YoMeVacuno"

        # Optional glob pattern of files which should be added to the commit
        #file_pattern: output/*/*.csv

        # Optional local file path to the repository
        repository: Datos-COVID19

        # Optional commit user and author settings
        commit_user_name: MinCiencia GitHub Actions Bot
        commit_user_email: actions@github.com
        commit_author: minciencia github bot <actions@github.com>

#    - name: update_API
#      run: |
#        curl -u "${{ secrets.DO_INT_USER }}:${{ secrets.DO_INT_PASS }}" \
#        -H 'Accept: application/vnd.github.everest-preview+json'  "https://api.github.com/repos/Data-Observatory/covid19-API/dispatches" \
#        -d '{"event_type": "update_please_from_reporte_diario"}'
