# This is a basic workflow to help you get started with Actions

name: Actualiza_info_campa帽a_vacunaci贸n

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
#    push:
#        branches: master
#        paths: 'input/ReporteDiario/*.csv'

    schedule:
      - cron:  '7 1-3 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Actualiza_productos_del_reporte_diario_p37_y_p46:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Sets up python
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
          python-version: 3.7

    # Runs a set of commands using the runners shell
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: generate products from Reporte Diario
      run: |
          cd src
          python vacunacion.py &&\
          python tweet.py ${{ secrets.TWITTER_API_KEY }} ${{ secrets.TWITTER_API_SECRET }}  \
                      ${{ secrets.TWITTER_ACCESS_TOKEN }}  ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }} \
                      "Actualic茅 los datos que dan cuenta del avance en la campa帽a de vacunaci贸n de hoy , gracias a la APS y al equipo de la Divisi贸n de Planificaci贸n Sanitaria del @ministeriosalud. Mira espec铆ficamente qu茅 actualic茅 en la imagen, y cl贸nate el github https://github.com/MinCiencia/Datos-COVID19"

    - uses: stefanzweifel/git-auto-commit-action@v4.1.1
      with:
        commit_message: "Added data from campa帽a de vacunacion"

        # Optional glob pattern of files which should be added to the commit
        file_pattern: output/*/*.csv

        # Optional local file path to the repository
        repository: .

        # Optional commit user and author settings
        commit_user_name: MinCiencia GitHub Actions Bot
        commit_user_email: actions@github.com
        commit_author: minciencia github bot <actions@github.com>


    - name: update_API
      run: |
        curl -u "${{ secrets.DO_INT_USER }}:${{ secrets.DO_INT_PASS }}" \
        -H 'Accept: application/vnd.github.everest-preview+json'  "https://api.github.com/repos/Data-Observatory/covid19-API/dispatches" \
        -d '{"event_type": "update_please_from_reporte_diario"}'
